# Generated by Django 2.2.4 on 2020-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apars', '0004_auto_20200404_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новое'), (2, 'Готово')], default=1, verbose_name='Статус задания'),
        ),
    ]
