# Generated by Django 2.2.4 on 2020-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apars', '0005_auto_20200404_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Задание', verbose_name='Название задания'),
        ),
    ]
