# Generated by Django 2.2.4 on 2020-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apars', '0006_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(unique=True, verbose_name='Название задания'),
        ),
    ]
